parameters:
    bxav_bell_api_client.api_url.param: https://localhost:8000/api
    bxav_bell_api_client.user_id.param: user_id
    bxav_bell_api_client.api_key.param: api_key

services:
    bxav_bellapi_client.resources_mapper:
        class: Bxav\Bundle\BellApiClientBundle\Model\ClassToResourceMapper
        calls:
          - [addClassToResoureMapping, ["business", "Bxav\Bundle\BellApiClientBundle\Model\Business", ["businesses", "{business}"]]]
          - [addClassToResoureMapping, ["booking", "Bxav\Bundle\BellApiClientBundle\Model\Booking", ["bookings", "{booking}"]]]
          - [addClassToResoureMapping, ["customer", "Bxav\Bundle\BellApiClientBundle\Model\Customer", ["customers", "{customer}"]]]
          - [addClassToResoureMapping, ["current/customer", "Bxav\Bundle\BellApiClientBundle\Model\Customer", ["current/customer"]]]
          - [addClassToResoureMapping, ["employee", "Bxav\Bundle\BellApiClientBundle\Model\Employee", ["employees", "{employee}"]]]
          - [addClassToResoureMapping, ["service", "Bxav\Bundle\BellApiClientBundle\Model\Service", ["businesses", "{business}", "services", , "{service}"]]]
          - [addClassToResoureMapping, ["availability", "Bxav\Bundle\BellApiClientBundle\Model\Availability", ["availabilities", "{availability}"], "string"]]

    bxav_bellapi_client.client:
        class: Bxav\Bundle\BellApiClientBundle\Model\BellApiClient
        arguments: 
          - @bxav_bell_api_client.guzzle_client
          - @serializer
          - @bxav_bellapi_client.resources_mapper
          - %bxav_bell_api_client.api_url.param%
          - %bxav_bell_api_client.user_id.param%
          - %bxav_bell_api_client.api_key.param%

        
    bxav_bell_api_client.guzzle_client:
        class: GuzzleHttp\Client