Bxav\Bundle\BellApiClientBundle\Model\Availability:
    exclusion_policy: ALL
    properties:
        date:
            expose: true
            type: DateTime
        service:
            expose: true
            type: Bxav\Bundle\BellApiClientBundle\Model\Service
        employees:
            expose: true
            type: array<Bxav\Bundle\BellApiClientBundle\Model\Employee>
