Bxav\Bundle\BellApiClientBundle\Model\Booking:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        startDatetime:
            expose: true
            type: DateTime
        endDatetime:
            expose: true
            type: DateTime
        price:
            expose: true
            type: float
        personalized:
            expose: true
            type: boolean
        customer:
            expose: true
            type: Bxav\Bundle\BellApiClientBundle\Model\Customer
        service:
            expose: true
            type: Bxav\Bundle\BellApiClientBundle\Model\Service
        employee:
            expose: true
            type: Bxav\Bundle\BellApiClientBundle\Model\Employee
