services:
    sonata.admin.business:
        class: AppBundle\Admin\BusinessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Business", label: "Business" }
        arguments:
            - ~
            - AppBundle\Entity\Business
            - ~
        calls:
            - [ setTemplate, [edit, :Admin:edit.html.twig]]
            - [ addChild, [@sonata.admin.address]]

    sonata.admin.address:
        class: AppBundle\Admin\AddressAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: "false", group: "Business", label: "Address" }
        arguments:
            - ~
            - AppBundle\Entity\Address
            - SonataAdminBundle:CRUD

    sonata.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Business", label: "Employee" }
        arguments:
            - ~
            - AppBundle\Entity\Employee
            - ~
        calls:
            - [ setTemplate, [edit, :Admin:edit.html.twig]]

    sonata.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Business", label: "Service" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~

    sonata.admin.booking:
        class: AppBundle\Admin\BookingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Booking", label: "Booking" }
        arguments:
            - ~
            - AppBundle\Entity\Booking
            - ~

    sonata.admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Booking", label: "Customer" }
        arguments:
            - ~
            - AppBundle\Entity\Customer
            - ~
