services:
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~

    sonata.admin.business:
        class: AppBundle\Admin\BusinessAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Business", label: "Business" }
        arguments:
            - ~
            - AppBundle\Entity\Business
            - ~
