users:
    type:     rest
    resource: AppBundle\Controller\Api\UserController

business:
    type:     rest
    resource: AppBundle\Controller\Api\BusinessController

business_service:
    type:     rest
    resource: AppBundle\Controller\Api\BusinessServiceController

employee:
    type:     rest
    resource: AppBundle\Controller\Api\EmployeeController

current_employee:
    type:     rest
    resource: AppBundle\Controller\Api\CurrentEmployeeController

booking:
    type:     rest
    resource: AppBundle\Controller\Api\BookingController

customer:
    type:     rest
    resource: AppBundle\Controller\Api\CustomerController

customer_personalized_service:
    type:     rest
    resource: AppBundle\Controller\Api\CustomerPersonalizedServiceController
