users:
    type:     rest
    resource: AppBundle\Controller\Api\UserController

business:
    type:     rest
    resource: AppBundle\Controller\Api\BusinessController

booking:
    type:     rest
    resource: AppBundle\Controller\Api\BookingController