users:
    type:     rest
    resource: AppBundle\Controller\Api\UserController

business:
    type:     rest
    resource: AppBundle\Controller\Api\BusinessController

employee:
    type:     rest
    resource: AppBundle\Controller\Api\EmployeeController

current_employee:
    type:     rest
    resource: AppBundle\Controller\Api\CurrentEmployeeController

booking:
    type:     rest
    resource: AppBundle\Controller\Api\BookingController

customer:
    type:     rest
    resource: AppBundle\Controller\Api\CustomerController

customer_personalization:
    type:     rest
    resource: AppBundle\Controller\Api\CustomerPersonalizationController
