_api:
    prefix:   /api
    resource: routing_api/main.yml


app_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

sylius_taxonomy:
    resource: @SyliusTaxonomyBundle/Resources/config/routing.yml
    prefix: /taxonomy


_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


app_web_security:
    resource: "@AppBundle/Controller/Web/SecurityController.php"
    type:     annotation
