_api:
    prefix:   /api
    resource: routing_api.yml


app_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/api

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_web_security:
    resource: "@AppBundle/Controller/Web/SecurityController.php"
    type:     annotation

app_web_default:
    resource: "@AppBundle/Controller/Web/DefaultController.php"
    type:     annotation

app_web_customer:
    resource: "@AppBundle/Controller/Web/CustomerController.php"
    type:     annotation

app_web_business:
    resource: "@AppBundle/Controller/Web/BusinessController.php"
    type:     annotation
