security:
    providers:
        user_provider:
            id: app.user.user_provider

    encoders:
        BxMarket\User\Model\UserInterface: sha512

    firewalls:
        rest_webservice:
            pattern: ^/api/.*
            stateless: true
            fos_oauth:  true
            anonymous:  true

        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                provider: user_provider
                success_handler: app.user.success_handler
            logout:       true
            anonymous:    true

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pro, role: ROLE_API }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_USER:   ROLE_API
        ROLE_EMPLOYEE: ROLE_USER
        ROLE_CUSTOMER: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_ADMINISTRATION_ACCESS: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_decision_manager:
        strategy: unanimous
