# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.user.success_handler.class: AppBundle\Authentication\SuccessHandler

services:
    app.listener.image.post_load:
        class: AppBundle\EventListener\SetRealPathFile
        arguments: [@request_stack]
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    app.user.success_handler:
        class: %app.user.success_handler.class%
        arguments: [@router]
        calls:
          - [setBackendUserRoles, [['ROLE_ADMIN', 'ROLE_SUPER_ADMIN']]]
          - [setAppProUserRoles, [['ROLE_EMPLOYEE']]]

    app.availability.finder:
        class: App\Availability\AvailabilityFinder
        arguments:
          - @=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:Booking')
          - @=service('doctrine.orm.default_entity_manager').getRepository('AppBundle:Employee')

    app.oauth2.client_creator:
        class: AppBundle\Api\ClientCreator
        arguments:
            - @fos_oauth_server.client_manager.default

    app.user.user_provider:
        class: App\User\UserProvider
        arguments:
            - @app.user.user_manager.user

    app.user.user_manager.user:
        class: App\User\Doctrine\UserManager
        arguments:
            - @security.encoder_factory
            - @doctrine.orm.default_entity_manager
            - AppBundle\Entity\User

    app.user.user_listener:
        class: App\User\Doctrine\Orm\UserListener
        public: false
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    app.image_uploader:
        class: AppBundle\Uploader\ImageUploader
        arguments:
            - @app.uploader.filesystem

    app.uploader.filesystem:
        class: Gaufrette\Filesystem
        factory: [@knp_gaufrette.filesystem_map, get]
        arguments:
            - app_image
