app_api_availability_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.availability:indexAction
        _format: json
        _sylius:
            criteria: { date: $date,  service: $service }
            authentication: false
