app_api_service_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.service:indexAction
        _format: json
        _sylius:
            paginate: $limit
            sortable: true

app_api_service_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: app.controller.service:showAction
        _format: json
        _sylius:
            authentication: false

app_api_service_create:
    path: /
    methods: [POST]
    defaults:
        _controller: app.controller.service:createAction
        _format: json
        _sylius:
            form: app_api_service

app_api_service_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: app.controller.service:updateAction
        _format: json
        _sylius:
            form: app_api_service

