app_api_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.user:indexAction
        _format: json
        _sylius:
            paginate: $limit
            sortable: true

app_api_user_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: app.controller.user:showAction
        _format: json

app_api_user_create:
    path: /
    methods: [POST]
    defaults:
        _controller: app.controller.user:createAction
        _format: json
        _sylius:
            form: app_api_user

app_api_user_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: app.controller.user:updateAction
        _format: json
        _sylius:
            form: app_api_user
