AppBundle\Entity\Employee:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [read, write]
        firstName:
            expose: true
            type: string
            groups: [read, write]
        lastName:
            expose: true
            type: string
            groups: [read, write]
        speciality:
            expose: true
            type: string
            groups: [read, write]
        shortDescription:
            expose: true
            type: string
            groups: [read, write]
        image:
            expose: true
            type: AppBundle\Entity\Image
            groups: [read]
        user:
            expose: true
            type: AppBundle\Entity\User
            groups: [read, write]
        business:
            expose: true
            type: AppBundle\Entity\Business
            groups: [read, write]
        workingDays:
            expose: true
            type: array
    relations:
        -
            rel: self
            href: expr('/api/employees/' ~ object.getId())
