AppBundle\Entity\Service:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        duration:
            expose: true
            type: integer
        type:
            expose: true
            type: string
        price:
            expose: true
            type: float
        description:
            expose: true
            type: string
        image:
            expose: true
            type: AppBundle\Entity\Image
        business:
            expose: true
            type: AppBundle\Entity\Business
    relations:
        -
            rel: self
            href: expr('/api/services/' ~ object.getId())