AppBundle\Entity\Customer:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [read, write]
        firstname:
            expose: true
            type: string
            groups: [read, write]
        lastname:
            expose: true
            type: string
            groups: [read, write]
        user:
            expose: true
            type: AppBundle\Entity\User
            groups: [read, write]