AppBundle\Entity\Business:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        name:
            expose: true
            type: string
        website:
            expose: true
            type: string
        phone:
            expose: true
            type: string
        email:
            expose: true
            type: string
        mainService:
            expose: true
            type: string
        availableBrands:
            expose: true
            type: string
        paymentMethods:
            expose: true
            type: string
        image:
            expose: true
            type: AppBundle\Entity\Image
        description:
            expose: true
            type: string
        disponibilityTimeSlot:
            expose: true
            type: integer
        slug:
            expose: true
            type: string
        workingDays:
            expose: true
            type: array
    virtual_properties:
        getMainAddress:
            serialized_name: main_address
            type: AppBundle\Entity\Address
