AppBundle\Entity\Service:
    services{1..5}:
        Type: <sentence()>
        Duration: <numberBetween(10, 45)>
        Price: <word()>
        Description: <sentence()>
        Employee: @employee1
