sylius_resource:
    resources:
        app.business:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\Business
                controller: AppBundle\Controller\Api\ApiController
        app.booking:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\Booking
                repository: AppBundle\Entity\BookingRepository
                controller: AppBundle\Controller\Api\BookingController
        app.user:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\User
                controller: AppBundle\Controller\Api\ApiController
        app.employee:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\Employee
                controller: AppBundle\Controller\Api\EmployeeController
        app.customer:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\Customer
                controller: AppBundle\Controller\Api\ApiController
        app.service:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\Service
                repository: AppBundle\Entity\ServiceRepository
                controller: AppBundle\Controller\Api\ServiceController
        app.personalized_service:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: AppBundle\Entity\PersonalizedService
                controller: AppBundle\Controller\Api\ApiController
        app.availability:
            driver: doctrine/orm
            object_manager: default
            templates: App:User
            classes:
                model: BxMarket\Availability\Model\Availability
                controller: AppBundle\Controller\Api\AvailabilityController